### ISSUE TITLE
1.0 release TO DO list

### ISSUE THREAD

**Issue by mkj-is** [xproduction/trianglam#2]
- [x] Splash screen
- [x] Gallery performance
- [x] Trashing animation improvement
- [x] Hexagons
- [x] iOS 6 icons
- [x] Blur view animation
- [x] Open in & camera icons
- [x] Sharing & open in
- [x] About screen?

**Comment by zvonicek** [comment]
- [x] Triangle as an activity indicator
- [x] Camera frame on 4-inch display

Nice to have:
- [x] UI rotation in camera
- [x] Take photo with volume button

**Comment by mkj-is** [comment]
More nice to have:
- [x] Localytics

**Comment by zvonicek** [comment]
- [x] Center share buttons in gallery

**Comment by mkj-is** [comment]
- [x] Uchovávání GPS

**Comment by mkj-is** [comment]
S trochou štěstí about screen nakreslím dnes a implementuju zítra, pokud nebudu mrtvý po tom slučáku…

A výpočty rámů musíme doladit s Dubrou.

**Comment by zvonicek** [comment]
Dnes jsem testoval Trianglam na bráchově 3GS / iOS 6 a fungovalo to skvěle, skoro lépe, než na mém i4. Myslím, že můžeme směle do světa.

**Comment by mkj-is** [comment]
To je skvělá zpráva. Mám to dát do App Store? Nebo tam ještě přidat about screen? Můžeme ho přidat ve verzi 1.0.1 ať už to nezdržujeme.

**Comment by zvonicek** [comment]
About screen myslím můžeme klidně nechat až na další verzi. Ještě navrhuju to otestovat na iPhone 5 a hned potom bych to dal do App Store. Nebo možná už přímo teď, ať chytnem místo ve frontě. Pokud bude s iPhonem 5 problém, můžeme to stáhnout a opravit.

A ještě jedna věc mě napadla - upravit text pro sdílení na Instagramu, aby obsahoval #troto a možná i @tranglam.

**Comment by mkj-is** [comment]
Otestováno na iPhone 5 a iPad 2. Posílám do App Store.
